//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleEchoBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int Id { get; set; }
        public string ConversationId { get; set; }
        public string UserName { get; set; }
        public string Channel { get; set; }
        public System.DateTime Created { get; set; }
        public string Message { get; set; }
    }
}
